# Copyright (c) 2026 John Horton
# SPDX-License-Identifier: GPL-2.0-only

# The game's sources, relative to game/: the core library and the SDL3
# frontend as game/CMakeLists.txt lists them, plus the Ogg decoder and
# main.c. A new source file goes in one of these lists.

# The game core: rules, world, data files, and the text interface.
set(AMMEROW_CORE_SOURCES
    src/artifact-balance-data.c
    src/artifact-lore-data.c
    src/buildid.c
    src/cave-map.c
    src/cave-square.c
    src/cave-view.c
    src/cave.c
    src/cmd-cave.c
    src/cmd-core.c
    src/cmd-fishing.c
    src/cmd-larder.c
    src/cmd-mode-policy.c
    src/cmd-misc.c
    src/cmd-obj.c
    src/cmd-pickup.c
    src/cmd-spelunking.c
    src/cmd-spoil.c
    src/cmd-wizard.c
    src/cmd-world.c
    src/datafile.c
    src/debug.c
    src/effect-handler-attack.c
    src/effect-handler-general.c
    src/effects.c
    src/effects-info.c
    src/fishing-data.c
    src/terrain-visual-data.c
    src/map-visual-data.c
    src/game-event.c
    src/game-input.c
    src/game-world.c
    src/world-data.c
    src/world-destination.c
    src/world-entry.c
    src/world-fishing.c
    src/world-fishing-discovery.c
    src/world-fishing-site.c
    src/world-generation.c
    src/world-larder.c
    src/world-larder-data.c
    src/relic-broker-data.c
    src/relic-broker.c
    src/relic-broker-save.c
    src/world-objective-data.c
    src/world-story-data.c
    src/world-location.c
    src/world-map.c
    src/world-object-transfer.c
    src/world-overworld.c
    src/world-spelunking.c
    src/world-spelunking-adapter.c
    src/world-spelunking-actor-data.c
    src/world-spelunking-breath.c
    src/world-spelunking-combat.c
    src/world-spelunking-codec.c
    src/world-spelunking-data-util.c
    src/world-spelunking-effects.c
    src/world-spelunking-inventory.c
    src/world-spelunking-layout.c
    src/world-spelunking-layout-data.c
    src/world-spelunking-local.c
    src/world-spelunking-population-data.c
    src/world-spelunking-generation.c
    src/world-spelunking-generation-endpoint.c
    src/world-spelunking-generation-geology.c
    src/world-spelunking-generation-population.c
    src/world-spelunking-generation-route.c
    src/world-spelunking-generation-system.c
    src/world-spelunking-generation-validation.c
    src/world-spelunking-generation-witness.c
    src/world-spelunking-geology-data.c
    src/world-spelunking-publication.c
    src/world-spelunking-passage.c
    src/world-spelunking-recipe-data.c
    src/world-spelunking-traversal-data.c
    src/world-spelunking-traversal-proof.c
    src/world-spelunking-water-data.c
    src/world-spelunking-runtime.c
    src/world-spelunking-system.c
    src/world-spelunking-system-data.c
    src/world-spelunking-transition.c
    src/world-spelunking-view.c
    src/world-spelunking-view-terrain.c
    src/world-spelunking-visibility.c
    src/world-travel-action.c
    src/world-travel-resources.c
    src/world-transition.c
    src/world-turn.c
    src/gen-cave.c
    src/gen-chunk.c
    src/gen-monster.c
    src/gen-room.c
    src/gen-util.c
    src/generate.c
    src/grafmode.c
    src/guid.c
    src/init.c
    src/load.c
    src/message.c
    src/mon-attack.c
    src/mon-blows.c
    src/mon-desc.c
    src/mon-group.c
    src/mon-init.c
    src/mon-list.c
    src/mon-lore.c
    src/mon-make.c
    src/mon-move.c
    src/mon-msg.c
    src/mon-predicate.c
    src/mon-spell.c
    src/mon-summon.c
    src/mon-timed.c
    src/mon-util.c
    src/obj-chest.c
    src/obj-curse.c
    src/obj-desc.c
    src/obj-gear.c
    src/obj-ignore.c
    src/obj-info.c
    src/obj-init.c
    src/obj-knowledge.c
    src/obj-list.c
    src/obj-make.c
    src/obj-pile.c
    src/obj-power.c
    src/obj-properties.c
    src/obj-randart.c
    src/obj-slays.c
    src/obj-tval.c
    src/obj-util.c
    src/option.c
    src/parser.c
    src/player-attack.c
    src/player-birth.c
    src/player-calcs.c
    src/player-class.c
    src/player-history.c
    src/player-path.c
    src/player-properties.c
    src/player-resource.c
    src/player-quest.c
    src/player-race.c
    src/player-spell.c
    src/player-timed.c
    src/player-util.c
    src/player.c
    src/project-feat.c
    src/project-mon.c
    src/project-obj.c
    src/project-player.c
    src/project.c
    src/randname.c
    src/save.c
    src/savefile.c
    src/score.c
    src/score-util.c
    src/sound-core.c
    src/source.c
    src/store.c
    src/target.c
    src/trap.c
    src/ui-birth.c
    src/ui-birth-screen.c
    src/ui-command.c
    src/ui-context.c
    src/ui-curse.c
    src/ui-death.c
    src/ui-display.c
    src/ui-effect.c
    src/ui-fishing.c
    src/ui-fishing-input.c
    src/ui-entry-combiner.c
    src/ui-entry-renderers.c
    src/ui-entry.c
    src/ui-equip-cmp.c
    src/ui-event.c
    src/ui-game.c
    src/ui-help.c
    src/ui-world-intro.c
    src/ui-history.c
    src/ui-history-screen.c
    src/ui-init.c
    src/ui-input.c
    src/ui-keymap.c
    src/ui-knowledge.c
    src/ui-knowledge-screen.c
    src/ui-map.c
    src/ui-menu.c
    src/ui-mode-input.c
    src/ui-nearby-screen.c
    src/ui-mon-list.c
    src/ui-mon-lore.c
    src/ui-obj-list.c
    src/ui-object.c
    src/ui-object-screen.c
    src/ui-options.c
    src/ui-output.c
    src/ui-player-properties.c
    src/ui-player.c
    src/ui-prefs.c
    src/ui-score.c
    src/ui-signals.c
    src/ui-spell.c
    src/ui-spoil.c
    src/ui-spelunking-appearance.c
    src/ui-spelunking.c
    src/ui-spelunking-input.c
    src/ui-spelunking-survey.c
    src/ui-store.c
    src/ui-store-screen.c
    src/ui-relic-broker.c
    src/ui-story.c
    src/ui-target.c
    src/ui-term.c
    src/ui-travel.c
    src/ui-world.c
    src/ui-visuals.c
    src/ui-wizard.c
    src/wiz-debug.c
    src/wiz-spoil.c
    src/wiz-stats.c
    src/z-bitflag.c
    src/z-color.c
    src/z-dice.c
    src/z-expression.c
    src/z-file.c
    src/z-form.c
    src/z-quark.c
    src/z-queue.c
    src/z-rand.c
    src/z-textblock.c
    src/z-type.c
    src/z-util.c
    src/z-virt.c
)

# The SDL3 frontend, which draws the game and plays its sound.
set(AMMEROW_SDL3_SOURCES
    src/main-sdl3.c
    src/snd-sdl3.c
    src/sdl3/audio.c
    src/sdl3/audio-wav.c
    src/sdl3/config.c
    src/sdl3/credits.c
    src/sdl3/dungeon-map-screen.c
    src/sdl3/effects.c
    src/sdl3/fishing.c
    src/sdl3/font.c
    src/sdl3/frontend-events.c
    src/sdl3/frontend-lifecycle.c
    src/sdl3/frontend-settings.c
    src/sdl3/home.c
    src/sdl3/world-intro.c
    src/sdl3/home-feature.c
    src/sdl3/home-layout.c
    src/sdl3/home-model.c
    src/sdl3/input.c
    src/sdl3/layout.c
    src/sdl3/legal.c
    src/sdl3/map-presenter.c
    src/sdl3/ascii-art.c
    src/sdl3/monster-art.c
    src/sdl3/inspect-card.c
    src/sdl3/inspect-card-presenter.c
    src/sdl3/monster-card-data.c
    src/sdl3/monster-card-layout.c
    src/sdl3/monster-card-presenter.c
    src/sdl3/monster-lore-screen.c
    src/sdl3/pause-menu.c
    src/sdl3/pause-menu-model.c
    src/sdl3/presentation.c
    src/sdl3/presenter.c
    src/sdl3/render.c
    src/sdl3/run-summary-screen.c
    src/sdl3/screen.c
    src/sdl3/screen-model.c
    src/sdl3/settings.c
    src/sdl3/settings-model.c
    src/sdl3/spelunking-presenter.c
    src/sdl3/store-art.c
    src/sdl3/terrain.c
    src/sdl3/tiles.c
    src/sdl3/term.c
    src/sdl3/theme.c
    src/sdl3/ui-draw.c
    src/sdl3/weather.c
    src/sdl3/world-map-screen.c
    src/sdl3/zoom.c
    src/sdl3/audio-ogg.c
    src/main.c
)
