# Ammerow modifications Copyright (c) 2026 John Horton
# SPDX-License-Identifier: GPL-2.0-only

#
# File: Makefile.src
#
# A makefile which includes the current object files, hopefully includable
# across a range of different makefiles, to cut down on maintenance.
#

NAME = Angband
VERSION = 4.2.6
COPYRIGHT = (c) 1995-2026 Angband contributors
PROGNAME = angband

HEADERS = \
	angband.h \
	artifact-balance-data.h \
	artifact-lore-data.h \
	cmd-core.h \
	cmd-fishing.h \
	cmd-larder.h \
	cmd-mode-policy.h \
	cmd-spelunking.h \
	cmds.h \
	config.h \
	effects.h \
	fishing-data.h \
	terrain-visual-data.h \
	map-visual-data.h \
	game-event.h \
	guid.h \
	h-basic.h \
	init.h \
	main.h \
	option.h \
	parser.h \
	ui-event.h \
	ui-fishing.h \
	ui-fishing-input.h \
	ui-history-screen.h \
	ui-knowledge-screen.h \
	ui-menu.h \
	ui-mode-input.h \
	ui-nearby-screen.h \
	ui-birth-screen.h \
	ui-object-screen.h \
	ui-store-screen.h \
	ui-relic-broker.h \
	ui-screen.h \
	ui-travel.h \
	ui-world.h \
	ui-world-intro.h \
	ui-spelunking.h \
	ui-spelunking-input.h \
	ui-spelunking-survey.h \
	wizard.h \
	world-data.h \
	world-destination.h \
	world-entry.h \
	world-fishing.h \
	world-fishing-discovery.h \
	world-fishing-site.h \
	world-generation.h \
	world-larder.h \
	world-larder-data.h \
	relic-broker-data.h \
	relic-broker.h \
	world-objective-data.h \
	world-location.h \
	world-map.h \
	world-object-transfer.h \
	world-overworld.h \
	world-spelunking.h \
	world-spelunking-adapter.h \
	world-spelunking-actor-data.h \
	world-spelunking-breath.h \
	world-spelunking-combat.h \
	world-spelunking-data-util.h \
	world-spelunking-effects.h \
	world-spelunking-inventory.h \
	world-spelunking-layout.h \
	world-spelunking-layout-data.h \
	world-spelunking-population-data.h \
	world-spelunking-local.h \
	world-spelunking-generation-endpoint.h \
	world-spelunking-generation-geology.h \
	world-spelunking-generation-population.h \
	world-spelunking-generation-route.h \
	world-spelunking-generation-system.h \
	world-spelunking-generation-witness.h \
	world-spelunking-generation.h \
	world-spelunking-geology-data.h \
	world-spelunking-perception.h \
	world-spelunking-passage.h \
	world-spelunking-publication.h \
	world-spelunking-recipe-data.h \
	world-spelunking-traversal-data.h \
	world-spelunking-traversal-proof.h \
	world-spelunking-water-data.h \
	world-spelunking-runtime.h \
	world-spelunking-system.h \
	world-spelunking-system-data.h \
	world-spelunking-transition.h \
	world-spelunking-view.h \
	world-spelunking-view-terrain.h \
	world-spelunking-visibility.h \
	world-travel-action.h \
	world-travel-resources.h \
	world-transition.h \
	world-turn.h \
	z-bitflag.h \
	z-color.h \
	z-dice.h \
	z-expression.h \
	z-file.h \
	z-form.h \
	z-quark.h \
	z-queue.h \
	z-rand.h \
	z-type.h \
	z-util.h \
	z-virt.h

ZFILES = \
	z-bitflag.o \
	z-color.o \
	z-dice.o \
	z-expression.o \
	z-file.o \
	z-form.o \
	z-quark.o \
	z-queue.o \
	z-rand.o \
	z-textblock.o \
	z-type.o \
	z-util.o \
	z-virt.o

# MAINFILES is defined by autotools (or manually) to be combinations of these

BASEMAINFILES = main.o

GCUMAINFILES = main-gcu.o

SDL2MAINFILES = \
	main-sdl2.o \
	sdl2/pui-ctrl.o \
	sdl2/pui-dlg.o \
	sdl2/pui-misc.o

SDLMAINFILES = main-sdl.o

SNDSDLFILES = snd-sdl.o

TESTMAINFILES = main-test.o

WINMAINFILES = \
        win/$(PROGNAME).res \
        main-win.o \
        win/readdib.o \
        win/readpng.o \
        win/scrnshot.o \
		win/win-layout.o

X11MAINFILES = main-x11.o

STATSMAINFILES = main-stats.o \
        stats/db.o

SPOILMAINFILES = main-spoil.o

# Remember all optional intermediates so "make clean" will get all of them
# even if the configuration has changed since a build was done.
ALLMAINFILES = \
	$(BASEMAINFILES) \
	$(GCUMAINFILES) \
	$(SDL2MAINFILES) \
	$(SDLMAINFILES) \
	$(SNDSDLFILES) \
	$(TESTMAINFILES) \
	$(WINMAINFILES) \
	$(X11MAINFILES) \
	$(STATSMAINFILES) \
	$(SPOILMAINFILES)

ANGFILES0 = \
	artifact-balance-data.o \
	artifact-lore-data.o \
	cave.o \
	cave-map.o \
	cave-square.o \
	cave-view.o \
	cmd-cave.o \
	cmd-core.o \
	cmd-fishing.o \
	cmd-larder.o \
	cmd-mode-policy.o \
	cmd-misc.o \
	cmd-obj.o \
	cmd-pickup.o \
	cmd-spelunking.o \
	cmd-spoil.o \
	cmd-wizard.o \
	cmd-world.o \
	datafile.o \
	debug.o \
	effect-handler-attack.o \
	effect-handler-general.o \
	effects.o \
	effects-info.o \
	fishing-data.o \
	terrain-visual-data.o \
	map-visual-data.o \
	game-event.o \
	game-input.o \
	game-world.o \
	world-data.o \
	world-story-data.o \
	ui-world-intro.o \
	world-destination.o \
	world-entry.o \
	world-fishing.o \
	world-fishing-discovery.o \
	world-fishing-site.o \
	world-generation.o \
	world-larder.o \
	world-larder-data.o \
	relic-broker-data.o \
	relic-broker.o \
	relic-broker-save.o \
	world-objective-data.o \
	world-location.o \
	world-map.o \
	world-object-transfer.o \
	world-overworld.o \
	world-spelunking.o \
	world-spelunking-adapter.o \
	world-spelunking-actor-data.o \
	world-spelunking-breath.o \
	world-spelunking-combat.o \
	world-spelunking-codec.o \
	world-spelunking-data-util.o \
	world-spelunking-effects.o \
	world-spelunking-inventory.o \
	world-spelunking-layout.o \
	world-spelunking-layout-data.o \
	world-spelunking-population-data.o \
	world-spelunking-local.o \
	world-spelunking-generation.o \
	world-spelunking-generation-endpoint.o \
	world-spelunking-generation-geology.o \
	world-spelunking-generation-population.o \
	world-spelunking-generation-route.o \
	world-spelunking-generation-system.o \
	world-spelunking-generation-validation.o \
	world-spelunking-generation-witness.o \
	world-spelunking-geology-data.o \
	world-spelunking-passage.o \
	world-spelunking-publication.o \
	world-spelunking-recipe-data.o \
	world-spelunking-traversal-data.o \
	world-spelunking-traversal-proof.o \
	world-spelunking-water-data.o \
	world-spelunking-runtime.o \
	world-spelunking-system.o \
	world-spelunking-system-data.o \
	world-spelunking-transition.o \
	world-spelunking-view.o \
	world-spelunking-view-terrain.o \
	world-spelunking-visibility.o \
	world-travel-action.o \
	world-travel-resources.o \
	world-transition.o \
	world-turn.o \
	generate.o \
	gen-cave.o \
	gen-chunk.o \
	gen-monster.o \
	gen-room.o \
	gen-util.o \
	grafmode.o \
	guid.o \
	init.o \
	load.o \
	message.o \
	mon-attack.o \
	mon-blows.o \
	mon-desc.o \
	mon-group.o \
	mon-init.o \
	mon-list.o \
	mon-lore.o \
	mon-make.o \
	mon-move.o \
	mon-msg.o \
	mon-predicate.o \
	mon-spell.o \
	mon-summon.o \
	mon-timed.o \
	mon-util.o \
	obj-chest.o \
	obj-curse.o \
	obj-desc.o \
	obj-gear.o \
	obj-ignore.o \
	obj-info.o \
	obj-init.o \
	obj-knowledge.o \
	obj-list.o \
	obj-make.o \
	obj-pile.o \
	obj-power.o \
	obj-properties.o \
	obj-randart.o \
	obj-slays.o \
	obj-tval.o \
	obj-util.o \
	option.o \
	parser.o \
	randname.o \
	player-attack.o \
	player-birth.o \
	player-calcs.o \
	player-class.o \
	player-history.o \
	player-path.o \
	player-properties.o \
	player-resource.o \
	player-quest.o \
	player-race.o \
	player-spell.o \
	player-timed.o \
	player-util.o \
	player.o \
	project.o \
	project-feat.o \
	project-mon.o \
	project-obj.o \
	project-player.o \
	save.o \
	savefile.o \
	score.o \
	score-util.o \
	sound-core.o \
	source.o \
	store.o \
	target.o \
	trap.o \
	ui-birth.o \
	ui-birth-screen.o \
	ui-command.o \
	ui-context.o \
	ui-curse.o \
	ui-death.o \
	ui-display.o \
	ui-effect.o \
	ui-fishing.o \
	ui-fishing-input.o \
	ui-entry.o \
	ui-entry-combiner.o \
	ui-entry-renderers.o \
	ui-equip-cmp.o \
	ui-event.o \
	ui-game.o \
	ui-help.o \
	ui-history.o \
	ui-history-screen.o \
	ui-init.o \
	ui-input.o \
	ui-keymap.o \
	ui-knowledge.o \
	ui-knowledge-screen.o \
	ui-map.o \
	ui-menu.o \
	ui-mode-input.o \
	ui-nearby-screen.o \
	ui-mon-list.o \
	ui-mon-lore.o \
	ui-obj-list.o \
	ui-object.o \
	ui-object-screen.o \
	ui-options.o \
	ui-output.o \
	ui-player-properties.o \
	ui-player.o \
	ui-prefs.o \
	ui-score.o \
	ui-signals.o \
	ui-spell.o \
	ui-spoil.o \
	ui-spelunking-appearance.o \
	ui-spelunking.o \
	ui-spelunking-input.o \
	ui-spelunking-survey.o \
	ui-store.o \
	ui-store-screen.o \
	ui-relic-broker.o \
	ui-story.o \
	ui-target.o \
	ui-term.o \
	ui-travel.o \
	ui-world.o \
	ui-visuals.o \
	ui-wizard.o \
	wiz-debug.o \
	wiz-spoil.o \
	wiz-stats.o

buildid.o: $(ANGFILES0)
ANGFILES = $(ANGFILES0) buildid.o
