#!/usr/bin/env python3
"""Generate anonymous randart slots plus stable Ammerow quest artefacts."""

# Copyright (c) 2026 John Horton
# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import argparse
from pathlib import Path
import sys


def directive(path: Path, key: str) -> str:
	prefix = f"{key}:"
	values = [line[len(prefix):].strip()
		for line in path.read_text(encoding="utf-8").splitlines()
		if line.startswith(prefix)]
	if len(values) != 1:
		raise ValueError(f"{path}: expected one {key!r} directive")
	return values[0]


def quest_records(path: Path) -> list[list[str]]:
	if directive(path, "origin") != "ammerow-original":
		raise ValueError("quest source is not marked ammerow-original")
	if directive(path, "review") != "release":
		raise ValueError("quest source is not marked release")
	records: list[list[str]] = []
	current: list[str] | None = None
	for line in path.read_text(encoding="utf-8").splitlines():
		if line.startswith("name:"):
			if current is not None:
				records.append(current)
			current = [line]
		elif current is not None:
			current.append(line)
	if current is not None:
		records.append(current)
	for record in records:
		if not any(line.startswith("base-object:") for line in record):
			raise ValueError("quest artefact is missing a base object")
		if not any(line.startswith("desc:") for line in record):
			raise ValueError("quest artefact is missing a description")
	return records


def render(balance: Path, quests: Path) -> str:
	if directive(balance, "origin") != "anonymous-aggregate":
		raise ValueError("balance source is not marked anonymous-aggregate")
	if directive(balance, "review") != "release":
		raise ValueError("balance source is not marked release")
	generated_slots = int(directive(balance, "generated-slots"))
	stable_slots = int(directive(balance, "stable-slots"))
	records = quest_records(quests)
	if generated_slots < 1 or stable_slots != len(records):
		raise ValueError("declared slot counts do not match quest source")

	lines = [
		"# Generated by utils/generate-artifact-slots.py.",
		"# Anonymous entries reserve runtime slots only; their mechanics and",
		"# identities are always replaced from reviewed aggregate/lore data.",
		"# Do not hand-edit this file.",
		"",
	]
	for index in range(1, generated_slots + 1):
		if index == 1:
			base_object = "base-object:ring:Ring"
			graphics = "graphics:=:d"
			weight = 2
			attack = "attack:0d0:0:0"
		elif index == 2:
			base_object = "base-object:amulet:Amulet"
			graphics = "graphics:\":d"
			weight = 3
			attack = "attack:0d0:0:0"
		else:
			base_object = "base-object:sword:Dagger"
			graphics = None
			weight = 10
			attack = "attack:1d4:0:0"
		lines.extend((
			f"name:'Calibration Slot {index:03d}'",
			base_object,
		))
		if graphics:
			lines.append(graphics)
		lines.extend((
			"level:1",
			f"weight:{weight}",
			"cost:0",
			"alloc:0:0 to 0",
			attack,
			"armor:0:0",
			"desc:Anonymous generated-artefact slot; never displayed in normal play.",
			"",
		))
	lines.extend(("", "### Stable Ammerow quest artefacts ###", ""))
	for record in records:
		lines.extend(record)
		if lines[-1]:
			lines.append("")
	return "\n".join(lines).rstrip() + "\n"


def main() -> int:
	root = Path(__file__).resolve().parents[1]
	parser = argparse.ArgumentParser()
	mode = parser.add_mutually_exclusive_group(required=True)
	mode.add_argument("--write", action="store_true")
	mode.add_argument("--check", action="store_true")
	parser.add_argument("--balance", type=Path,
		default=root / "lib/gamedata/artifact_balance.txt")
	parser.add_argument("--quests", type=Path,
		default=root / "lib/authoring/artifact_quest.txt")
	parser.add_argument("--output", type=Path,
		default=root / "lib/gamedata/artifact.txt")
	args = parser.parse_args()
	expected = render(args.balance.resolve(), args.quests.resolve())
	if args.write:
		args.output.parent.mkdir(parents=True, exist_ok=True)
		args.output.write_text(expected, encoding="utf-8", newline="\n")
		return 0
	actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
	if actual != expected:
		print(f"generated artifact slot file is stale: {args.output}", file=sys.stderr)
		return 1
	print(f"generated artifact slot file OK: {args.output}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
